### ISSUE TITLE
Assuming people's gender without their permission

### ISSUE THREAD

**Issue by tsirolnik** [alison985/awesome-men#3]
Hi!

Can you please not assume someone's gender? 
Please add a reference to a **gender statement/permission** from these people. 
It's not nice to dictate someone's gender. 

Thanks in advance.

**Comment by alison985** [comment]
Everyone on the list I either know personally or submitted a PR to add themselves.

**Comment by tsirolnik** [comment]
Thanks ❤️ 👋 🐸 💯
