### ISSUE TITLE
Misleading repo contents

### ISSUE THREAD

**Issue by tsirolnik** [alison985/awesome-men#4]
Hi again,

I've waited a day to see if the code tab will have actual code in it, but I couldn't find any code nor anything related to coding. The only thing that remotely related is the Code of Conduct file which has the word code in it.

I'm not sure if it's against Github's rules or not, but, it's a bit misleading.

I'd be happy if you'd add a clarification to the README.md file so people will know that you're using Github code hosting for non-related stuff, as again, it's a bit misleading.

Appreciated!

**Comment by alison985** [comment]
None of the other non-code repos on Github include such a note.
